### ISSUE TITLE
library version 

### ISSUE THREAD

**Issue by ZhiliangWu** [robertomest/neural-style-keras#2]
Could you please share the library version of the used keras and tensorflow. I tried to played around with the older versions of keras but there are always some errors. Thanks a lot in advance.

**Comment by robertomest** [comment]
Hello Zhiliang, unfortunately I am not 100% sure of the exact versions I used. If I am not mistaken it should work with Tensorflow 0.10 and Keras 1. I think the lastest version before Keras 2 should be fine, which is 1.2.2. I apologize for not having a more precise answer. Feel free to message me again if this does not help you so that we can try to figure it out.

**Comment by ZhiliangWu** [comment]
Hello robert, thanks for reply the message. I tried the tensofrflow 0.10.0 with keras 1.2.2, installing the package with `conda install`. Here are the message I got:
```bash
$ python fast_style_transfer.py --checkpoint_path data/models/candy.h5 --input_path content_imgs/brad_pitt.jpg --output_path test.jpg --use_style_name --gpu -1
Using TensorFlow backend.
Creating pastiche model...
Traceback (most recent call last):
  File "fast_style_transfer.py", line 50, in <module>
    targets=class_targets)
  File "/Users/zhiliangwu/Gitlab/neural-style-keras/model.py", line 63, in pastiche_model
    o = conv(x, 16 * k, kernel_size=9, nb_classes=nb_classes, targets=targets)
  File "/Users/zhiliangwu/Gitlab/neural-style-keras/model.py", line 26, in conv
    o = ReflectionPadding2D(padding=(pad, pad))(x)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/zhiliangwu/Gitlab/neural-style-keras/layers.py", line 17, in call
    return tf.pad(x, pattern, mode='REFLECT')
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1330, in pad
    name=name)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1262, in _mirror_pad
    mode=mode, name=name)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 454, in apply_op
    as_ref=input_arg.is_ref)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/zhiliangwu/miniconda3/envs/style-keras/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 4.0 of type 'float' instead.
```
Do you have any idea about it?

**Comment by robertomest** [comment]
It seems to me the problem is not on the libraries, but the fact that you are using python 3. The code was made for python 2 and was not tested on python 3. [The line that computes the padding](https://github.com/robertomest/neural-style-keras/blob/master/model.py#L25) is returning a float because `/` in python 2 is integer division and in python 3 it is float division. If using python 2.7 is not a problem for you, I would recommend it. Otherwise, changing it to `pad = (kernel_size - 1) / 2` should fix the problem. Let me know how it works for you.

**Comment by ZhiliangWu** [comment]
Thanks for your reply. It works perfect under Python2.7. 
Here is the summary of the requirements:
```
tensorflow==0.10.0
keras==1.2.2
pillow==5.2.0
```
Really appreciate your instant reply and great implementation.

**Comment by robertomest** [comment]
No problem! Feel free to contact me if you need anything else.
